src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentRepository::class)]
class Comment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column(nullable: true)]
    private ?int $likes = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Post $post_parent = null;

    #[ORM\ManyToOne(targetEntity: self::class, inversedBy: 'comments')]
    private ?self $comment_parent = null;

    #[ORM\OneToMany(mappedBy: 'comment_parent', targetEntity: self::class)]
    private Collection $comments;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $create_at = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $delete_at = null;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $author = null;

    #[ORM\Column(length: 255)]
    private ?string $status = null;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getLikes(): ?int
    {
        return $this->likes;
    }

    public function setLikes(?int $likes): self
    {
        $this->likes = $likes;

        return $this;
    }

    public function getPostParent(): ?Post
    {
        return $this->post_parent;
    }

    public function setPostParent(?Post $post_parent): self
    {
        $this->post_parent = $post_parent;

        return $this;
    }

    public function getCommentParent(): ?self
    {
        return $this->comment_parent;
    }

    public function setCommentParent(?self $comment_parent): self
    {
        $this->comment_parent = $comment_parent;

        return $this;
    }

    /**
     * @return Collection<int, self>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(self $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setCommentParent($this);
        }

        return $this;
    }

    public function removeComment(self $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getCommentParent() === $this) {
                $comment->setCommentParent(null);
            }
        }

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeInterface $create_at): self
    {
        $this->create_at = $create_at;

        return $this;
    }

    public function getDeleteAt(): ?\DateTimeInterface
    {
        return $this->delete_at;
    }

    public function setDeleteAt(?\DateTimeInterface $delete_at): self
    {
        $this->delete_at = $delete_at;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }
}

src/Form/CommentType.php
<?php

namespace App\Form;

use App\Entity\Comment;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('content', TextareaType::class)
            ->add('submit',
                SubmitType::class,
                [
                    'attr' => [
                        'class' => 'btn btn-primary shadow-sm hover:bg-indigo-700 bg-indigo-600'
                    ]
                ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Comment::class,
        ]);
    }
}

src/Controller/CommentController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Form\CommentType;
use App\Repository\CommentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/comment')]
class CommentController extends AbstractController
{
    #[Route('/', name: 'app_comment_index', methods: ['GET'])]
    public function index(CommentRepository $commentRepository): Response
    {
        return $this->render('comment/index.html.twig', [
            'comments' => $commentRepository->findAll(),
        ]);
    }

    public function new(): Comment
    {
        $comment = new Comment();
        $comment->setAuthor($this->getUser());
        $comment->setCreateAt(new \DateTime());
        $comment->setLikes(0);
//        $form = $this->createForm(CommentType::class, $comment);
//        $form->handleRequest($request);

//        if ($form->isSubmitted() && $form->isValid()) {
//            $commentRepository->save($comment, true);
//
//            return $this->redirectToRoute('app_comment_index', [], Response::HTTP_SEE_OTHER);
//        }

//        return $this->renderForm('comment/new.html.twig', [
//            'comment' => $comment,
//            'form' => $form,
//        ]);
        //redirect to post
        return $comment;
    }

    #[Route('/{id}', name: 'app_comment_show', methods: ['GET'])]
    public function show(Comment $comment): Response
    {
        return $this->render('comment/show.html.twig', [
            'comment' => $comment,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_comment_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Comment $comment, CommentRepository $commentRepository): Response
    {
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $commentRepository->save($comment, true);

            return $this->redirectToRoute('app_comment_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('comment/edit.html.twig', [
            'comment' => $comment,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_comment_delete', methods: ['POST'])]
    public function delete(Request $request, Comment $comment, CommentRepository $commentRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$comment->getId(), $request->request->get('_token'))) {
            $commentRepository->remove($comment, true);
        }

        return $this->redirectToRoute('app_comment_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/comment/_delete_form.html.twig
<form method="post" action="{{ path('app_comment_delete', {'id': comment.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ comment.id) }}">
    <button class="btn">Delete</button>
</form>

templates/comment/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/comment/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Comment{% endblock %}

{% block body %}
    <h1>Edit Comment</h1>

    {{ include('comment/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_comment_index') }}">back to list</a>

    {{ include('comment/_delete_form.html.twig') }}
{% endblock %}

templates/comment/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Comment index{% endblock %}

{% block body %}
    <h1>Comment index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Content</th>
                <th>Likes</th>
                <th>Create_at</th>
                <th>Delete_at</th>
                <th>Status</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for comment in comments %}
            <tr>
                <td>{{ comment.id }}</td>
                <td>{{ comment.content }}</td>
                <td>{{ comment.likes }}</td>
                <td>{{ comment.createAt ? comment.createAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ comment.deleteAt ? comment.deleteAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ comment.status }}</td>
                <td>
                    <a href="{{ path('app_comment_show', {'id': comment.id}) }}">show</a>
                    <a href="{{ path('app_comment_edit', {'id': comment.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_comment_new') }}">Create new</a>
{% endblock %}

templates/comment/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Comment{% endblock %}

{% block body %}
    <h1>Create new Comment</h1>

    {{ include('comment/_form.html.twig') }}

    <a href="{{ path('app_comment_index') }}">back to list</a>
{% endblock %}

templates/comment/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Comment{% endblock %}

{% block body %}
    <h1>Comment</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ comment.id }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ comment.content }}</td>
            </tr>
            <tr>
                <th>Likes</th>
                <td>{{ comment.likes }}</td>
            </tr>
            <tr>
                <th>Create_at</th>
                <td>{{ comment.createAt ? comment.createAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Delete_at</th>
                <td>{{ comment.deleteAt ? comment.deleteAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ comment.status }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_comment_index') }}">back to list</a>

    <a href="{{ path('app_comment_edit', {'id': comment.id}) }}">edit</a>

    {{ include('comment/_delete_form.html.twig') }}
{% endblock %}